{% set name = "opentelemetry-instrumentation-starlette" %}
{% set version = "0.37b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_starlette-{{ version }}.tar.gz
  sha256: 5ec9adbf59486a58dbb825662b06ecfd7edc49a25ac71873b56f01924be56cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-asgi ==0.37b0
    - opentelemetry-instrumentation ==0.37b0
    - opentelemetry-semantic-conventions ==0.37b0
    - opentelemetry-util-http ==0.37b0
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette
  summary: OpenTelemetry Starlette Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
